name: ESG-Restful CI/CD to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Run Tests with Maven
        run: mvn -B clean install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ESG-Restful-App
          path: target/*.jar

  deploy-staging:
    name: Deploy to Azure App Service (Staging)
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: staging

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ESG-Restful-App

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          package: '*.jar'
          java-version: '21'

  deploy-production:
    name: Deploy to Azure App Service (Production)
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production


    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ESG-Restful-App

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          package: '*.jar'
          java-version: '21'